# Generated by Django 4.2.3 on 2023-07-31 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('IC', 'Ice-Creams'), ('CZ', 'Cheese'), ('CR', 'Curd'), ('MS', 'MilkShake'), ('GH', 'Ghee'), ('PN', 'Paneer'), ('ML', 'Milk')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('discounted_price', models.FloatField()),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('West-Bengal', 'West-Bengal'), ('Uttar-Pradesh', 'Uttar-Pradesh'), ('Tamilnadu', 'Tamilnadu'), ('Gujrat', 'Gujrat'), ('Maharashtra', 'Maharashtra')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
